const accessoriesController = require("../app/controllers/AccessoriesController")
const middlewareController = require("../app/controllers/MiddlewareController")
const imgFunc = require("../config/db/upload")
const router = require("express").Router()

router.get("/all-accessories", middlewareController.verifyToken, accessoriesController.showAllAccessory)
router.get("/all-accessories-for-customer", middlewareController.verifyToken, accessoriesController.getAllAccessoryForCus)
router.get("/all-accessories-by-type", middlewareController.verifyToken, accessoriesController.showAllAccessoryByType)
router.post("/new-accessory", middlewareController.verifyTokenManager, accessoriesController.createNewAccessory)
router.post("/new-supplier", middlewareController.verifyTokenManager, accessoriesController.createSupplier)
router.get("/accessory-img/:filename", imgFunc.getImg)
router.post("/upload-img/:id", middlewareController.verifyTokenManager, accessoriesController.deleteImgAccessories, accessoriesController.updateImgAccessories)
router.get("/detail-accessory/:id", middlewareController.verifyTokenStaff, accessoriesController.getAccessory)
router.patch("/upadated-accessory/:id", middlewareController.verifyTokenManager, accessoriesController.updateAccessory)
module.exports = router
