const accountController = require("../app/controllers/AccountController")
const middlewareController = require("../app/controllers/MiddlewareController")
const router = require("express").Router()

router.get("/all", middlewareController.verifyTokenManager, accountController.getAllAccounts)
router.get("/account-detail", middlewareController.verifyTokenManager, accountController.getAllAccountsDetail)
router.get("/view-profile", middlewareController.verifyToken, accountController.viewOwnedProfile)
router.get("/view-booking-history", middlewareController.verifyToken, accountController.viewBookingHistory)
router.get("/:username", middlewareController.verifyTokenManager, accountController.getAccountByUsername)
router.get("/all/lastest-account", middlewareController.verifyTokenManager, accountController.showLastestAccount)
router.get("/byId/:id", middlewareController.verifyTokenManager, accountController.getAccountById)
router.patch('/change-password', middlewareController.verifyToken, accountController.updateAccountById)
router.patch("/editprofile", middlewareController.verifyToken, accountController.updateProfileAccount)
router.post("/register-staff", accountController.registerAccountStaff)
router.post("/editimgprofile",/* middlewareController.verifyToken,*/ accountController.updateImgProfileAccount)
router.patch("/:id/restore", middlewareController.verifyTokenManager,  accountController.restoreAccount)
router.delete("/:id", middlewareController.verifyTokenAdmin, accountController.deleteAccount)
module.exports = router
