const router = require("express").Router()
const bookingController = require('../app/controllers/BookingController')
const middlewareController = require("../app/controllers/MiddlewareController")

router.get('/all', middlewareController.verifyTokenManager, bookingController.showAll)
router.get('/with-order-status/all', middlewareController.verifyTokenManager, bookingController.showAllBookingWithOrderInfo)
router.get('/all/bookings-account', middlewareController.verifyToken, bookingController.showAllBookingByAccount)
router.get('/search/:id', middlewareController.verifyTokenStaff, bookingController.searchBookingById)
router.post('/create', middlewareController.verifyToken, bookingController.createBookingCustomer)
router.post('/create-booking-manager', middlewareController.verifyTokenManager, bookingController.createBookingManager)
router.put('/update/:id', middlewareController.verifyToken, bookingController.updateBookingByIdForCus)
router.patch('/accpet-booking', middlewareController.verifyTokenManager, bookingController.acceptBooking)
router.patch('/cancel-booking', middlewareController.verifyToken, bookingController.cancelBooking)
router.get('/booking-by-id/:id', middlewareController.verifyTokenManager, bookingController.showAllBookingByCusId)
router.get('/:id', middlewareController.verifyToken, bookingController.getBookingByIdForCus)
router.put('/:id', middlewareController.verifyTokenManager, bookingController.updateBookingById)
module.exports = router
