const router = require("express").Router()
const orderController = require('../app/controllers/OrderController')
const middlewareController = require("../app/controllers/MiddlewareController")
router.get('/test1', orderController.showAllServiceToChoose)
router.get('/test', orderController.addDetailOrder)
router.get('/all', /*middlewareController.verifyTokenManager,*/ orderController.showAllOrder)
router.get('/:id', orderController.searchOrderById)
router.patch('/:id', orderController.updateOrderById)
router.patch('/accpet-order', orderController.acceptOrder)
router.patch('/complete-order', orderController.completeOrder)
router.patch('/cancel-order', orderController.cancelOrder)
module.exports = router
