const router = require("express").Router()
const orderController = require('../app/controllers/OrderController')
const middlewareController = require("../app/controllers/MiddlewareController")
router.get('/show-service-to-choose',middlewareController.verifyTokenStaff, orderController.showAllServiceToChoose)
router.get('/all', middlewareController.verifyTokenManager, orderController.showAllOrder)
router.get('/:id', middlewareController.verifyTokenManager, orderController.searchOrderById)
router.get('/cus/:id', middlewareController.verifyToken, orderController.getOrderByIdForCus)
router.patch('/:id', middlewareController.verifyTokenStaff, orderController.updateOrderById)
router.patch('/accept-order', middlewareController.verifyTokenManager, orderController.acceptOrder)
router.patch('/complete-order', middlewareController.verifyTokenStaff, orderController.completeOrder)
router.patch('/cancel-order', middlewareController.verifyTokenStaff, orderController.cancelOrder)
router.post('/add-detail-order/:id', middlewareController.verifyTokenStaff, orderController.addDetailOrder)
router.get('/get-order-total-price/:id', middlewareController.verifyTokenStaff, orderController.getTotalPrice)
module.exports = router
