const router = require("express").Router()
const scheduleController = require('../app/controllers/ScheduleController')
const middlewareController = require("../app/controllers/MiddlewareController")

router.post('/assignslot', middlewareController.verifyTokenStaff, scheduleController.assignWorkSlot)
router.get('/allschedule', scheduleController.showWorkSchedule)
router.get('/schedule-no-order', scheduleController.showScheduleWithoutOrder)
router.get('/show-slot',middlewareController.verifyTokenStaff, scheduleController.showWorkSlotForAssign)
router.get('/oneweekschedule', scheduleController.getOneWeekSchedule)
router.patch('/assign-slot-to-order', middlewareController.verifyTokenManager, scheduleController.assignWorkSlotToOrder)
router.get('/show-workslot-for-assign', middlewareController.verifyTokenManager, scheduleController.showWorkSlotForAssign)
router.get('/show-workslot', middlewareController.verifyTokenStaff, scheduleController.showWorkSlotStaff)
router.get('/show-workslot-thisweek', middlewareController.verifyTokenStaff, scheduleController.showOneWeekWorkStaff)
router.get('/show-schedule-for-assign', scheduleController.showScheduleForAssign)
router.get('/work-slot/:id', middlewareController.verifyTokenManager, scheduleController.showWorkSlotByStaffId)
router.get('/order-working-history', middlewareController.verifyTokenStaff, scheduleController.showOrderWorkingHistory)
router.patch('/staff-in-work/:id', middlewareController.verifyTokenStaff, scheduleController.stillBusyStaff)
module.exports = router
